### ISSUE TITLE
Periodic mail checks.

### ISSUE THREAD

**Issue by VlaK0r** [h33n0k/nl2rss#3]
Hello! 
Thank you for your work! 
Please tell me, what is the frequency of checking mail and how can it be changed?

**Comment by h33n0k** [comment]
The application does not rely on a fixed check frequency. Instead, it maintains a persistent connection to the IMAP server. As soon as a new email reaches your inbox, the application instantly saves the article.

Do you experience any issue related to any kind of delay ?

**Comment by VlaK0r** [comment]
I send test emails to my mailbox, but they do not appear in the application.

**Comment by h33n0k** [comment]
Have you checked the container logs ?
Did they ended up in the selected mail box ? [`IMAP_BOX`](https://github.com/h33n0k/nl2rss?tab=readme-ov-file#environment)

**Comment by VlaK0r** [comment]
When the container is launched, emails are scanned and added to the application. But in the process of work, new letters do not appear.

**Comment by h33n0k** [comment]
can you pull the development branch ? to the latest commit ? https://github.com/h33n0k/nl2rss/commit/884554a89ccd07f2ac6213fa324c12bd9a8e91df

**Comment by VlaK0r** [comment]
Can you tell me how to do this? I'm just learning))

**Comment by h33n0k** [comment]
cd into your directory and run the folowing command:
```bash
git pull origin development
```

then rebuild your container
```bash
docker compose build
```

**Comment by VlaK0r** [comment]
![изображение](https://github.com/user-attachments/assets/7587f31c-236f-419e-9fa5-70516e1df0d7)
Now in the logs there is information that Mails fetched. But there are no changes in the web interface.

**Comment by VlaK0r** [comment]
> can you pull the issue related branch ?
> 
> ```shell
> git fetch origin
> git pull 3-periodic-mail-checks
> docker compose build
> ```

![изображение](https://github.com/user-attachments/assets/2762736c-46a7-49d4-a574-c6f9c42f4740)

**Comment by h33n0k** [comment]
just pull the branch 3-periodic-mail-checks

**Comment by VlaK0r** [comment]
![изображение](https://github.com/user-attachments/assets/afbbeec2-e00e-4bd1-ac00-9c49d504bf7a)
Do I need to enter a port for the database?

**Comment by h33n0k** [comment]
In production, it’s not necessary for the application to connect to the database via an exposed port, as both are typically on the same Docker network. Exposing the database port is primarily intended for development or monitoring purposes but is not recommended, especially when running in a Docker container, due to security risks.

**Comment by VlaK0r** [comment]
> In production, it’s not necessary for the application to connect to the database via an exposed port, as both are typically on the same Docker network. Exposing the database port is primarily intended for development or monitoring purposes but is not recommended, especially when running in a Docker container, due to security risks.

That is, it does not affect the operation of the container in any way?

**Comment by h33n0k** [comment]
Exposing the database outside the container does not affect the operation of the container itself. It simply makes the database accessible from outside the container. However, in production, the application typically connects to the database within the same Docker network, so exposing the port is unnecessary.

**Comment by VlaK0r** [comment]
I forgot to ask. Is there a timer set to log out?

**Comment by h33n0k** [comment]
Thank you for contributing to the improvement of this project! I’m currently working on other projects but will return to update this one soon. 🤞

**Comment by h33n0k** [comment]
yeah the access token expires after a certain period you can see the default configuration [here](https://github.com/h33n0k/nl2rss/blob/development/config/default.ts)

**Comment by VlaK0r** [comment]
Unfortunately, the problem remained.
Judging by the logs, this happens after some actions with the database. Maybe I'm wrong.

`nl2rss-database  | 2024-12-10 09:00:20+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.6.2+maria~ubu2404 started.
nl2rss-database  | 2024-12-10 09:00:21+00:00 [Warn] [Entrypoint]: /sys/fs/cgroup///memory.pressure not writable, functionality unavailable to MariaDB
nl2rss-database  | 2024-12-10 09:00:21+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
nl2rss-database  | 2024-12-10 09:00:22+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.6.2+maria~ubu2404 started.
nl2rss-database  | 2024-12-10 09:00:23+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] Starting MariaDB 11.6.2-MariaDB-ubu2404 source revision d8dad8c3b54cd09fefce7bc3b9749f427eed9709 server_uid LCg2dmk9vFFgLj1RkFZlGMdR5GA= as process 1
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: Compressed tables use zlib 1.3
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: Number of transaction pools: 1
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: Using ARMv8 crc32 instructions
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
nl2rss-database  | 2024-12-10  9:00:23 0 [Warning] mariadbd: io_uring_queue_init() failed with errno 95
nl2rss-database  | 2024-12-10  9:00:23 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: Completed initialization of buffer pool
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: End of log at LSN=172120
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: Opened 3 undo tablespaces
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: log sequence number 172120; transaction id 322
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] Plugin 'FEEDBACK' is disabled.
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] Plugin 'wsrep-provider' is disabled.
nl2rss-database  | 2024-12-10  9:00:23 0 [Note] InnoDB: Buffer pool(s) load completed at 241210  9:00:23
nl2rss-database  | 2024-12-10  9:00:31 0 [Note] Server socket created on IP: '0.0.0.0'.
nl2rss-database  | 2024-12-10  9:00:31 0 [Note] Server socket created on IP: '::'.
nl2rss-database  | 2024-12-10  9:00:31 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
nl2rss-database  | 2024-12-10  9:00:31 0 [Note] mariadbd: ready for connections.
nl2rss-database  | Version: '11.6.2-MariaDB-ubu2404'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution`

**Comment by VlaK0r** [comment]
I tried everything. Everything was removed, reinstalled, cleaned. Nothing helps.

**Comment by h33n0k** [comment]
> Unfortunately, the problem remained.

What problem ? Could you provide a more detailed description please ?

**Comment by VlaK0r** [comment]
> > Unfortunately, the problem remained.
> 
> What problem ? Could you provide a more detailed description please ?

Processes emails only when the container is launched and for some time. Further, when receiving an email, the program sees it but does not process it, does not create an html file.
